spring.application.name=demo-service

# ---- Server config ----
server.port=8080

# --- Use local Postgres in Docker ---
spring.datasource.url=jdbc:postgresql://localhost:5432/FirstGo
spring.datasource.username=postgres
spring.datasource.password=pizzafruit1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
