spring.application.name=demo-service

# ---- Server config ----
server.port=8080

# --- Use local Postgres in Docker ---
spring.datasource.url=jdbc:postgresql://localhost:5432/FirstGo
spring.datasource.username=postgres
spring.datasource.password=pizzafruit1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Exceptions
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


# --- JWT config ---
security.jwt.secret=VGhpcy1NeS1TdXBlci1Mb25nLUJhc2U2NC1TZWNyZXQhMTIzNDU2Nzg
security.jwt.expiration=3000000 # in milliseconds (3000000 ms = 50 minutes)
